tasks:
  - init: |
      nvm install 14.17.2
      npm install
      npm install -g hexo-cli
      npm install -g grunt-cli
vscode:
  extensions:
    - PKief.material-icon-theme
    - HookyQR.beautify
    - kamikillerto.vscode-colorize
    - formulahendry.auto-close-tag
    - formulahendry.auto-complete-tag
    - formulahendry.auto-rename-tag
    - eliostruyf.vscode-front-matter
    - https://fantasy.gallery.vsassets.io/_apis/public/gallery/publisher/fantasy/extension/vscode-hexo-utils/0.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage