tasks:
  - init: |
      nvm install 14.17.2
      npm install
      npm install -g hexo-cli
      npm install -g grunt-cli
vscode:
  extensions:
    - PKief.material-icon-theme
    - HookyQR.beautify
    - kamikillerto.vscode-colorize
    - formulahendry.auto-close-tag
    - formulahendry.auto-complete-tag
    - formulahendry.auto-rename-tag
    - eliostruyf.vscode-front-matter
    - https://fantasy.gallery.vsassets.io/_apis/public/gallery/publisher/fantasy/extension/vscode-hexo-utils/0.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod