tasks:
  - init: |
      nvm install 14.17.2
      npm install
      npm install -g hexo-cli
      npm install -g grunt-cli
vscode:
  extensions:
    - https://fantasy.gallery.vsassets.io/_apis/public/gallery/publisher/fantasy/extension/vscode-hexo-utils/0.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage