# Header
nav_menu:
  home: /
  search: /search
  archives: /archives
  series: /series
  notes: /notes
  photos: /photos
  tiny-tools: /collections/tiny-tools
  projects: /projects
  about: /about
  feeds: /feeds

footer_menu:
  about: /about
  impressum: /impressum
  feeds: /feeds

# Content
excerpt_link: Continue reading ...

# Sidebar
sidebar: right
widgets:
- about
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - archive
# - tagcloud

# widget behavior
archive_type: 'monthly'
show_count: true
recent_posts_count: 4

# Miscellaneous
favicon: /favicon.ico
