# Header
nav_menu:
  home: /
  archives: /archives
  series: /series
  projects: /projects
  til: /til
  tiny-tools: /collections/tiny-tools
  rss: /atom.xml

footer_menu:
  about: /about
  rss: /atom.xml
  photos: /photos

# Content
excerpt_link: Continue reading ...

# Sidebar
sidebar: right
widgets:
- about
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - archive
# - tagcloud

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
