# Header
nav_menu:
  # home: /
  search: /search
  articles: /archives
  notes: /notes
  photos: /photos
  apps: /apps
  projects: /projects
  tools: /tools/tiny-tools
  feeds: /feeds
  about: /about

footer_menu:
  about: /about
  impressum: /impressum
  feeds: /feeds

# Content
excerpt_link: Continue reading ...

# Sidebar
sidebar: right
widgets:
- about
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - archive
# - tagcloud

# widget behavior
archive_type: 'monthly'
show_count: true
recent_posts_count: 4

# Miscellaneous
favicon: /favicon.ico
